language: node_js
node_js:
    - lts/*

cache:
  directories:
    - "node_modules"
    
install:
    - npm install

script:
    - echo "Skipping tests"
    - npm run build

notifications:
    email: thinkwave@gmail.com

deploy:
    provider: pages
    skip-cleanup: true
    local_dir: public
    github-token: $GITHUB_TOKEN
    repo: thinkwave/thinkwave.github.io
    keep-history: true
    target-branch: main
    on:
        branch: main